name: How to Start a Non Profit
favicon: null
layout_spectrum: 0.7485635888297111
typography_spectrum: 0.27471833070740104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1b1a'
    - '#9a9997'
    - '#676360'
    - '#fcc200'
  brandStrength: 0.3125
  lightness: 0.3080593303311616
  saturation: 0.13977308687753975
  rhythmicContrast: 0.1123826673720032
purpose: []
