name: How to Start a Non Profit
favicon: null
layout_spectrum: 0.49924
typography_spectrum: 0.74627
title: 'From zero to one million dollars raised- from somebody that actually did it. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1b1a'
    - '#9a9997'
    - '#676360'
    - '#fcc200'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
